import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react';
import styles from '../styles/Home.module.css'


export default function Home() {

  const payload={
    prompt:"a photograph of an astronaut riding a horse",
    // steps:1,
    steps:5,
  };
  const [resultURL,setResultURL]=useState<string>("");
  const [resultInfo,setResultInfo]=useState<string>("loading...");
  

  useEffect(()=>{

    fetch(
      '/sdapi/v1/txt2img',{
        method:"POST",
        headers:{
          "Content-Type":"application/json",
        },
        body:JSON.stringify(payload),
      })
      .then((res) => res.json())
      .then((data) => {
        console.log(data);
        // setResultURL("https://dummyimage.com/256x256/000/fff.png");
        if(data.images && 0<data.images.length){
          setResultURL(`data:image/png;base64,${data.images[0]}`);
          setResultInfo(data.info);
        }else{
          setResultInfo("no images");
        }
      });

  },[]);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <figure className={styles.figure}>
          <Image className={styles.figureImage} src={resultURL?resultURL:"https://dummyimage.com/256x256/000/fff.png?text=loading..."} alt="" width="256" height="256" />
          <figcaption  className={styles.figureFigcaption}>{resultInfo}</figcaption>
        </figure>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
